package app

import (
	"encoding/json"
	"net/http"
	"strings"
	"time"

	"github.com/Saurrabhh/splittr_be/docs"
	"github.com/Saurrabhh/splittr_be/internal/response"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	httpSwagger "github.com/swaggo/http-swagger/v2"
	swagV1 "github.com/swaggo/swag"
)

// cleanOneOf recursively walks the parsed OpenAPI schema map and simplifies any
// requestBody schema that uses an unnecessary "oneOf" wrapper with an empty object type
// and the actual model reference (generated by swag v2), so that Swagger UI can correctly
// display the request body example structure.
func cleanOneOf(m map[string]interface{}) {
	for k, v := range m {
		if k == "schema" {
			if schemaMap, ok := v.(map[string]interface{}); ok {
				if oneOf, ok := schemaMap["oneOf"].([]interface{}); ok && len(oneOf) == 2 {
					first, ok1 := oneOf[0].(map[string]interface{})
					second, ok2 := oneOf[1].(map[string]interface{})
					if ok1 && ok2 && first["type"] == "object" {
						if ref, okRef := second["$ref"].(string); okRef {
							m["schema"] = map[string]interface{}{
								"$ref": ref,
							}
						}
					}
				}
			}
		}
		if childMap, ok := v.(map[string]interface{}); ok {
			cleanOneOf(childMap)
		} else if childSlice, ok := v.([]interface{}); ok {
			for _, item := range childSlice {
				if itemMap, ok := item.(map[string]interface{}); ok {
					cleanOneOf(itemMap)
				}
			}
		}
	}
}

func init() {
	// Downgrade the OpenAPI version from 3.1.0 to 3.0.0 since the embedded Swagger UI in
	// http-swagger does not yet support 3.1.0 specs and fails to load it.
	template := strings.Replace(docs.SwaggerInfo.SwaggerTemplate, `"openapi": "3.1.0"`, `"openapi": "3.0.0"`, 1)

	// Post-process the generated template to clean up the request body schemas.
	// swag v2 generates an unnecessary 'oneOf' wrapper for request bodies containing
	// an empty object type and the actual referenced schema, which prevents Swagger UI from
	// displaying the request body example. We unwrap this to point directly to the $ref.
	// We replace `{{ marshal .Schemes }}` with a valid JSON placeholder `[]` temporarily
	// to make the string valid JSON for unmarshaling.
	templateJSON := strings.Replace(template, `{{ marshal .Schemes }}`, `[]`, 1)

	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(templateJSON), &parsed); err == nil {
		cleanOneOf(parsed)
		if cleanedBytes, err := json.Marshal(parsed); err == nil {
			cleanedStr := string(cleanedBytes)
			// Restore the original Go template expression
			cleanedStr = strings.Replace(cleanedStr, `"schemes":[]`, `"schemes": {{ marshal .Schemes }}`, 1)
			cleanedStr = strings.Replace(cleanedStr, `"schemes": []`, `"schemes": {{ marshal .Schemes }}`, 1)
			template = cleanedStr
		}
	}

	// Register the OpenAPI spec (from swag/v2) to the swag v1 registry (which http-swagger uses)
	swagV1.Register(docs.SwaggerInfo.InstanceName(), &swagV1.Spec{
		Version:          docs.SwaggerInfo.Version,
		Host:             docs.SwaggerInfo.Host,
		BasePath:         docs.SwaggerInfo.BasePath,
		Schemes:          docs.SwaggerInfo.Schemes,
		Title:            docs.SwaggerInfo.Title,
		Description:      docs.SwaggerInfo.Description,
		InfoInstanceName: docs.SwaggerInfo.InfoInstanceName,
		SwaggerTemplate:  template,
		LeftDelim:        docs.SwaggerInfo.LeftDelim,
		RightDelim:       docs.SwaggerInfo.RightDelim,
	})
}

// routes configures global middlewares, defines route groups, and mounts handlers.
func (app *Application) routes(deps *dependencies) http.Handler {
	r := chi.NewRouter()

	// Global Middleware
	r.Use(middleware.RequestID)
	r.Use(middleware.ClientIPFromRemoteAddr)
	r.Use(middleware.Logger)
	r.Use(middleware.Recoverer)
	r.Use(middleware.Timeout(60 * time.Second))

	// Default/root route
	r.Get("/", app.rootHandler)

	// Health check route
	r.Get("/health", app.healthCheckHandler)

	// Swagger UI route
	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.DefaultModelsExpandDepth(2),
		httpSwagger.URL("/swagger/doc.json"),
	))

	// API version 1 routes
	r.Route("/v1", func(r chi.Router) {
		// Register domain-specific routes
		deps.userHandler.RegisterRoutes(r, deps.authMiddleware.Authenticate)

		// Group routes (requires authentication & local user resolution)
		r.Group(func(r chi.Router) {
			r.Use(deps.authMiddleware.Authenticate)
			r.Use(deps.userHandler.UserContext)
			deps.groupHandler.RegisterRoutes(r)
		})

		// Expense routes (requires authentication & local user resolution)
		r.Group(func(r chi.Router) {
			r.Use(deps.authMiddleware.Authenticate)
			r.Use(deps.userHandler.UserContext)
			deps.expenseHandler.RegisterRoutes(r)
		})

		// Activity routes (requires authentication & local user resolution)
		r.Group(func(r chi.Router) {
			r.Use(deps.authMiddleware.Authenticate)
			r.Use(deps.userHandler.UserContext)
			deps.activityHandler.RegisterRoutes(r)
		})

		// Notification routes (requires authentication & local user resolution)
		r.Group(func(r chi.Router) {
			r.Use(deps.authMiddleware.Authenticate)
			r.Use(deps.userHandler.UserContext)
			deps.notificationHandler.RegisterRoutes(r)
		})
	})

	// Custom 404 Not Found handler using response package
	r.NotFound(func(w http.ResponseWriter, r *http.Request) {
		response.NotFound(w, "endpoint not found")
	})

	return r
}
