package app

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/Saurrabhh/splittr_be/docs"
	"github.com/Saurrabhh/splittr_be/internal/response"
	"github.com/go-chi/chi/v5"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

// registerSwaggerRoutes registers all Swagger-related routes.
func registerSwaggerRoutes(r chi.Router) {
	// Redirect /docs to /swagger/index.html
	r.Get("/docs", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/swagger/index.html", http.StatusMovedPermanently)
	})

	// Serve swagger.json / doc.json directly to avoid registry mismatch between swag/v2 and http-swagger/v2
	r.Get("/swagger/doc.json", func(w http.ResponseWriter, r *http.Request) {
		doc := docs.SwaggerInfo.ReadDoc()
		// Swagger UI in http-swagger v2 doesn't support OpenAPI 3.1.0 yet and requires 3.0.n
		doc = strings.Replace(doc, `"openapi": "3.1.0"`, `"openapi": "3.0.0"`, 1)
		// Clean up the oneOf wrappers generated by swag/v2 to allow examples and bodies to render correctly in Swagger UI
		doc = cleanSwaggerJSON(doc)
		response.JSON(w, http.StatusOK, json.RawMessage(doc))
	})

	// Swagger UI route
	r.Get("/swagger/*", httpSwagger.Handler(
		httpSwagger.DefaultModelsExpandDepth(2),
		httpSwagger.URL("/swagger/doc.json"),
	))
}

// cleanSwaggerJSON removes the incorrect oneOf wrappers generated by swag/v2 for request bodies,
// enabling Swagger UI to correctly render the request body schemas and examples.
func cleanSwaggerJSON(input string) string {
	var doc map[string]interface{}
	if err := json.Unmarshal([]byte(input), &doc); err != nil {
		return input
	}

	paths, ok := doc["paths"].(map[string]interface{})
	if !ok {
		return input
	}

	for _, pathItemVal := range paths {
		pathItem, ok := pathItemVal.(map[string]interface{})
		if !ok {
			continue
		}
		for _, methodVal := range pathItem {
			method, ok := methodVal.(map[string]interface{})
			if !ok {
				continue
			}
			reqBody, ok := method["requestBody"].(map[string]interface{})
			if !ok {
				continue
			}
			content, ok := reqBody["content"].(map[string]interface{})
			if !ok {
				continue
			}
			for _, mediaTypeVal := range content {
				mediaType, ok := mediaTypeVal.(map[string]interface{})
				if !ok {
					continue
				}
				schema, ok := mediaType["schema"].(map[string]interface{})
				if !ok {
					continue
				}
				oneOf, ok := schema["oneOf"].([]interface{})
				if !ok || len(oneOf) != 2 {
					continue
				}

				var refStr string
				hasEmptyObj := false
				for _, itemVal := range oneOf {
					item, ok := itemVal.(map[string]interface{})
					if !ok {
						continue
					}
					if t, ok := item["type"].(string); ok && t == "object" && len(item) == 1 {
						hasEmptyObj = true
					} else if ref, ok := item["$ref"].(string); ok {
						refStr = ref
					}
				}

				if hasEmptyObj && refStr != "" {
					delete(schema, "oneOf")
					schema["$ref"] = refStr
				}
			}
		}
	}

	output, err := json.Marshal(doc)
	if err != nil {
		return input
	}
	return string(output)
}
