package app

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/Saurrabhh/splittr_be/docs"
	"github.com/Saurrabhh/splittr_be/internal/response"
	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	httpSwagger "github.com/swaggo/http-swagger/v2"
)

// registerSwaggerRoutes registers all Swagger-related routes protected by Basic Authentication.
func (app *Application) registerSwaggerRoutes(r chi.Router) {
	swaggerAuth := middleware.BasicAuth("Splittr Swagger Docs", map[string]string{
		app.Config.SwaggerUser: app.Config.SwaggerPassword,
	})

	// Apply auth to swagger routes group
	r.Route("/swagger", func(r chi.Router) {
		r.Use(swaggerAuth)

		// Serve swagger.json / doc.json directly to avoid registry mismatch between swag/v2 and http-swagger/v2
		r.Get("/doc.json", func(w http.ResponseWriter, r *http.Request) {
			doc := docs.SwaggerInfo.ReadDoc()
			// Swagger UI in http-swagger v2 doesn't support OpenAPI 3.1.0 yet and requires 3.0.n
			doc = strings.Replace(doc, `"openapi": "3.1.0"`, `"openapi": "3.0.0"`, 1)
			// Clean up the oneOf wrappers generated by swag/v2 to allow examples and bodies to render correctly in Swagger UI
			doc = cleanSwaggerJSON(doc)
			response.JSON(w, http.StatusOK, json.RawMessage(doc))
		})

		// Swagger UI route with custom operation method sorting within tags (GET -> POST -> PUT -> PATCH -> DELETE)
		r.Get("/*", httpSwagger.Handler(
			httpSwagger.DefaultModelsExpandDepth(2),
			httpSwagger.URL("/swagger/doc.json"),
			httpSwagger.UIConfig(map[string]string{
				"operationsSorter": "(a, b) => { const order = {'get': 1, 'post': 2, 'put': 3, 'patch': 4, 'delete': 5}; return (order[a.get('method')] || 99) - (order[b.get('method')] || 99); }",
			}),
		))
	})

	// Redirect /docs to /swagger/index.html (also protected)
	r.With(swaggerAuth).Get("/docs", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, "/swagger/index.html", http.StatusMovedPermanently)
	})
}

// cleanSwaggerJSON removes the incorrect oneOf wrappers generated by swag/v2 for request bodies,
// enabling Swagger UI to correctly render the request body schemas and examples.
func cleanSwaggerJSON(input string) string {
	var doc map[string]any
	if err := json.Unmarshal([]byte(input), &doc); err != nil {
		return input
	}

	paths, ok := doc["paths"].(map[string]any)
	if !ok {
		return input
	}

	for _, pathItemVal := range paths {
		pathItem, ok := pathItemVal.(map[string]any)
		if !ok {
			continue
		}
		for _, methodVal := range pathItem {
			method, ok := methodVal.(map[string]any)
			if !ok {
				continue
			}
			reqBody, ok := method["requestBody"].(map[string]any)
			if !ok {
				continue
			}
			content, ok := reqBody["content"].(map[string]any)
			if !ok {
				continue
			}
			for _, mediaTypeVal := range content {
				mediaType, ok := mediaTypeVal.(map[string]any)
				if !ok {
					continue
				}
				schema, ok := mediaType["schema"].(map[string]any)
				if !ok {
					continue
				}
				oneOf, ok := schema["oneOf"].([]any)
				if !ok || len(oneOf) != 2 {
					continue
				}

				var refStr string
				hasEmptyObj := false
				for _, itemVal := range oneOf {
					item, ok := itemVal.(map[string]any)
					if !ok {
						continue
					}
					if t, ok := item["type"].(string); ok && t == "object" && len(item) == 1 {
						hasEmptyObj = true
					} else if ref, ok := item["$ref"].(string); ok {
						refStr = ref
					}
				}

				if hasEmptyObj && refStr != "" {
					delete(schema, "oneOf")
					schema["$ref"] = refStr
				}
			}
		}
	}

	output, err := json.Marshal(doc)
	if err != nil {
		return input
	}
	return string(output)
}
