// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (id, group_id, actor_id, action_type, description, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, group_id, actor_id, action_type, description, created_at
`

type CreateActivityParams struct {
	ID          uuid.UUID
	GroupID     pgtype.UUID
	ActorID     pgtype.UUID
	ActionType  string
	Description string
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.ID,
		arg.GroupID,
		arg.ActorID,
		arg.ActionType,
		arg.Description,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ActorID,
		&i.ActionType,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createActivityVisibility = `-- name: CreateActivityVisibility :exec
INSERT INTO activity_visibility (activity_id, user_id)
VALUES ($1, $2)
`

type CreateActivityVisibilityParams struct {
	ActivityID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) CreateActivityVisibility(ctx context.Context, arg CreateActivityVisibilityParams) error {
	_, err := q.db.Exec(ctx, createActivityVisibility, arg.ActivityID, arg.UserID)
	return err
}

const listUserActivities = `-- name: ListUserActivities :many
SELECT a.id, a.group_id, a.actor_id, a.action_type, a.description, a.created_at, u.name as actor_name
FROM activities a
LEFT JOIN users u ON a.actor_id = u.id
WHERE 
    a.group_id IN (
        SELECT gm.group_id FROM group_members gm WHERE gm.user_id = $1
    )
    OR
    (a.group_id IS NULL AND EXISTS (
        SELECT 1 FROM activity_visibility av WHERE av.activity_id = a.id AND av.user_id = $1
    ))
ORDER BY a.created_at DESC
`

type ListUserActivitiesRow struct {
	ID          uuid.UUID
	GroupID     pgtype.UUID
	ActorID     pgtype.UUID
	ActionType  string
	Description string
	CreatedAt   pgtype.Timestamptz
	ActorName   pgtype.Text
}

func (q *Queries) ListUserActivities(ctx context.Context, userID uuid.UUID) ([]ListUserActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listUserActivities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserActivitiesRow
	for rows.Next() {
		var i ListUserActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.ActorID,
			&i.ActionType,
			&i.Description,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
