// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (id, description, amount, currency, category, group_id, paid_by, created_by, is_payment, spent_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW())
RETURNING id, description, amount, currency, category, group_id, paid_by, created_by, is_payment, spent_at, created_at, updated_at, deleted_at
`

type CreateExpenseParams struct {
	ID          uuid.UUID
	Description string
	Amount      pgtype.Numeric
	Currency    string
	Category    string
	GroupID     pgtype.UUID
	PaidBy      uuid.UUID
	CreatedBy   uuid.UUID
	IsPayment   bool
	SpentAt     pgtype.Timestamptz
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.ID,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.Category,
		arg.GroupID,
		arg.PaidBy,
		arg.CreatedBy,
		arg.IsPayment,
		arg.SpentAt,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Category,
		&i.GroupID,
		&i.PaidBy,
		&i.CreatedBy,
		&i.IsPayment,
		&i.SpentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createExpenseSplit = `-- name: CreateExpenseSplit :exec
INSERT INTO expense_splits (expense_id, user_id, amount, split_type, split_value)
VALUES ($1, $2, $3, $4, $5)
`

type CreateExpenseSplitParams struct {
	ExpenseID  uuid.UUID
	UserID     uuid.UUID
	Amount     pgtype.Numeric
	SplitType  string
	SplitValue pgtype.Numeric
}

func (q *Queries) CreateExpenseSplit(ctx context.Context, arg CreateExpenseSplitParams) error {
	_, err := q.db.Exec(ctx, createExpenseSplit,
		arg.ExpenseID,
		arg.UserID,
		arg.Amount,
		arg.SplitType,
		arg.SplitValue,
	)
	return err
}

const deleteExpense = `-- name: DeleteExpense :exec
UPDATE expenses
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteExpense(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpense, id)
	return err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, description, amount, currency, category, group_id, paid_by, created_by, is_payment, spent_at, created_at, updated_at, deleted_at
FROM expenses
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetExpenseByID(ctx context.Context, id uuid.UUID) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Category,
		&i.GroupID,
		&i.PaidBy,
		&i.CreatedBy,
		&i.IsPayment,
		&i.SpentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFriendBalances = `-- name: GetFriendBalances :many
SELECT 
    friend.id AS friend_id,
    friend.name AS friend_name,
    CAST(COALESCE(owed_to_me.amount, 0.00) - COALESCE(owed_by_me.amount, 0.00) AS NUMERIC) AS net_balance
FROM users friend
LEFT JOIN (
    SELECT es.user_id AS friend_id, SUM(es.amount) AS amount
    FROM expense_splits es
    JOIN expenses e ON es.expense_id = e.id
    WHERE e.paid_by = $1 AND e.group_id IS NULL AND e.deleted_at IS NULL AND es.user_id != $1
    GROUP BY es.user_id
) owed_to_me ON friend.id = owed_to_me.friend_id
LEFT JOIN (
    SELECT e.paid_by AS friend_id, SUM(es.amount) AS amount
    FROM expense_splits es
    JOIN expenses e ON es.expense_id = e.id
    WHERE e.paid_by != $1 AND e.group_id IS NULL AND e.deleted_at IS NULL AND es.user_id = $1
    GROUP BY e.paid_by
) owed_by_me ON friend.id = owed_by_me.friend_id
WHERE friend.id != $1 AND (owed_to_me.amount IS NOT NULL OR owed_by_me.amount IS NOT NULL)
`

type GetFriendBalancesRow struct {
	FriendID   uuid.UUID
	FriendName string
	NetBalance pgtype.Numeric
}

func (q *Queries) GetFriendBalances(ctx context.Context, paidBy uuid.UUID) ([]GetFriendBalancesRow, error) {
	rows, err := q.db.Query(ctx, getFriendBalances, paidBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendBalancesRow
	for rows.Next() {
		var i GetFriendBalancesRow
		if err := rows.Scan(&i.FriendID, &i.FriendName, &i.NetBalance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupBalances = `-- name: GetGroupBalances :many
SELECT 
    u.id AS user_id,
    u.name AS user_name,
    CAST(COALESCE(paid.total_paid, 0.00) - COALESCE(owed.total_owed, 0.00) AS NUMERIC) AS net_balance
FROM users u
JOIN group_members gm ON u.id = gm.user_id AND gm.group_id = $1
LEFT JOIN (
    SELECT paid_by, SUM(amount) AS total_paid
    FROM expenses
    WHERE group_id = $1 AND deleted_at IS NULL
    GROUP BY paid_by
) paid ON u.id = paid.paid_by
LEFT JOIN (
    SELECT es.user_id, SUM(es.amount) AS total_owed
    FROM expense_splits es
    JOIN expenses e ON es.expense_id = e.id
    WHERE e.group_id = $1 AND e.deleted_at IS NULL
    GROUP BY es.user_id
) owed ON u.id = owed.user_id
`

type GetGroupBalancesRow struct {
	UserID     uuid.UUID
	UserName   string
	NetBalance pgtype.Numeric
}

func (q *Queries) GetGroupBalances(ctx context.Context, groupID uuid.UUID) ([]GetGroupBalancesRow, error) {
	rows, err := q.db.Query(ctx, getGroupBalances, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupBalancesRow
	for rows.Next() {
		var i GetGroupBalancesRow
		if err := rows.Scan(&i.UserID, &i.UserName, &i.NetBalance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupPairwiseDebts = `-- name: GetGroupPairwiseDebts :many
SELECT 
    e.paid_by AS creditor_id,
    c.name AS creditor_name,
    es.user_id AS debtor_id,
    d.name AS debtor_name,
    CAST(SUM(es.amount) AS NUMERIC) AS total_amount
FROM expense_splits es
JOIN expenses e ON es.expense_id = e.id
JOIN users c ON e.paid_by = c.id
JOIN users d ON es.user_id = d.id
WHERE e.group_id = $1 AND e.deleted_at IS NULL AND es.user_id != e.paid_by
GROUP BY e.paid_by, c.name, es.user_id, d.name
`

type GetGroupPairwiseDebtsRow struct {
	CreditorID   uuid.UUID
	CreditorName string
	DebtorID     uuid.UUID
	DebtorName   string
	TotalAmount  pgtype.Numeric
}

func (q *Queries) GetGroupPairwiseDebts(ctx context.Context, groupID pgtype.UUID) ([]GetGroupPairwiseDebtsRow, error) {
	rows, err := q.db.Query(ctx, getGroupPairwiseDebts, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupPairwiseDebtsRow
	for rows.Next() {
		var i GetGroupPairwiseDebtsRow
		if err := rows.Scan(
			&i.CreditorID,
			&i.CreditorName,
			&i.DebtorID,
			&i.DebtorName,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenseSplits = `-- name: ListExpenseSplits :many
SELECT expense_id, user_id, amount, split_type, split_value, u.name, u.email, u.phone
FROM expense_splits es
JOIN users u ON es.user_id = u.id
WHERE es.expense_id = $1
`

type ListExpenseSplitsRow struct {
	ExpenseID  uuid.UUID
	UserID     uuid.UUID
	Amount     pgtype.Numeric
	SplitType  string
	SplitValue pgtype.Numeric
	Name       string
	Email      pgtype.Text
	Phone      pgtype.Text
}

func (q *Queries) ListExpenseSplits(ctx context.Context, expenseID uuid.UUID) ([]ListExpenseSplitsRow, error) {
	rows, err := q.db.Query(ctx, listExpenseSplits, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpenseSplitsRow
	for rows.Next() {
		var i ListExpenseSplitsRow
		if err := rows.Scan(
			&i.ExpenseID,
			&i.UserID,
			&i.Amount,
			&i.SplitType,
			&i.SplitValue,
			&i.Name,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByGroup = `-- name: ListExpensesByGroup :many
SELECT id, description, amount, currency, category, group_id, paid_by, created_by, is_payment, spent_at, created_at, updated_at
FROM expenses
WHERE group_id = $1 AND deleted_at IS NULL
ORDER BY spent_at DESC
`

type ListExpensesByGroupRow struct {
	ID          uuid.UUID
	Description string
	Amount      pgtype.Numeric
	Currency    string
	Category    string
	GroupID     pgtype.UUID
	PaidBy      uuid.UUID
	CreatedBy   uuid.UUID
	IsPayment   bool
	SpentAt     pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListExpensesByGroup(ctx context.Context, groupID pgtype.UUID) ([]ListExpensesByGroupRow, error) {
	rows, err := q.db.Query(ctx, listExpensesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpensesByGroupRow
	for rows.Next() {
		var i ListExpensesByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.GroupID,
			&i.PaidBy,
			&i.CreatedBy,
			&i.IsPayment,
			&i.SpentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFriendExpenses = `-- name: ListUserFriendExpenses :many
SELECT DISTINCT e.id, e.description, e.amount, e.currency, e.category, e.group_id, e.paid_by, e.created_by, e.is_payment, e.spent_at, e.created_at, e.updated_at
FROM expenses e
JOIN expense_splits es ON e.id = es.expense_id
WHERE e.group_id IS NULL 
  AND e.deleted_at IS NULL
  AND (e.paid_by = $1 OR es.user_id = $1)
  AND (
      SELECT COUNT(*) 
      FROM expense_splits es2 
      WHERE es2.expense_id = e.id
  ) > 1
ORDER BY e.spent_at DESC
`

type ListUserFriendExpensesRow struct {
	ID          uuid.UUID
	Description string
	Amount      pgtype.Numeric
	Currency    string
	Category    string
	GroupID     pgtype.UUID
	PaidBy      uuid.UUID
	CreatedBy   uuid.UUID
	IsPayment   bool
	SpentAt     pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

// Retrieve direct (non-group) splits between current user and any other user
func (q *Queries) ListUserFriendExpenses(ctx context.Context, paidBy uuid.UUID) ([]ListUserFriendExpensesRow, error) {
	rows, err := q.db.Query(ctx, listUserFriendExpenses, paidBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserFriendExpensesRow
	for rows.Next() {
		var i ListUserFriendExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.GroupID,
			&i.PaidBy,
			&i.CreatedBy,
			&i.IsPayment,
			&i.SpentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPersonalExpenses = `-- name: ListUserPersonalExpenses :many
SELECT e.id, e.description, e.amount, e.currency, e.category, e.group_id, e.paid_by, e.created_by, e.is_payment, e.spent_at, e.created_at, e.updated_at
FROM expenses e
WHERE e.paid_by = $1 
  AND e.group_id IS NULL 
  AND e.deleted_at IS NULL
  AND (
      SELECT COUNT(*) 
      FROM expense_splits es 
      WHERE es.expense_id = e.id
  ) = 1
ORDER BY e.spent_at DESC
`

type ListUserPersonalExpensesRow struct {
	ID          uuid.UUID
	Description string
	Amount      pgtype.Numeric
	Currency    string
	Category    string
	GroupID     pgtype.UUID
	PaidBy      uuid.UUID
	CreatedBy   uuid.UUID
	IsPayment   bool
	SpentAt     pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

// Retrieve expenses logged purely for personal budgeting (paid by user, and user is the ONLY split member)
func (q *Queries) ListUserPersonalExpenses(ctx context.Context, paidBy uuid.UUID) ([]ListUserPersonalExpensesRow, error) {
	rows, err := q.db.Query(ctx, listUserPersonalExpenses, paidBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserPersonalExpensesRow
	for rows.Next() {
		var i ListUserPersonalExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Category,
			&i.GroupID,
			&i.PaidBy,
			&i.CreatedBy,
			&i.IsPayment,
			&i.SpentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
