// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id, role, status, joined_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (group_id, user_id) 
DO UPDATE SET role = EXCLUDED.role, status = EXCLUDED.status, joined_at = NOW()
`

type AddGroupMemberParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
	Role    string
	Status  string
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember,
		arg.GroupID,
		arg.UserID,
		arg.Role,
		arg.Status,
	)
	return err
}

const archiveGroup = `-- name: ArchiveGroup :exec
UPDATE groups
SET archived_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ArchiveGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveGroup, id)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name, description, invite_code, invite_code_expires_at, require_admin_approval, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), NOW())
RETURNING id, name, description, invite_code, invite_code_expires_at, require_admin_approval, created_by, created_at, updated_at, archived_at
`

type CreateGroupParams struct {
	ID                   uuid.UUID
	Name                 string
	Description          pgtype.Text
	InviteCode           pgtype.Text
	InviteCodeExpiresAt  pgtype.Timestamptz
	RequireAdminApproval bool
	CreatedBy            pgtype.UUID
}

type CreateGroupRow struct {
	ID                   uuid.UUID
	Name                 string
	Description          pgtype.Text
	InviteCode           pgtype.Text
	InviteCodeExpiresAt  pgtype.Timestamptz
	RequireAdminApproval bool
	CreatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (CreateGroupRow, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.InviteCode,
		arg.InviteCodeExpiresAt,
		arg.RequireAdminApproval,
		arg.CreatedBy,
	)
	var i CreateGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.InviteCodeExpiresAt,
		&i.RequireAdminApproval,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, description, invite_code, invite_code_expires_at, require_admin_approval, created_by, created_at, updated_at, archived_at
FROM groups
WHERE id = $1 AND archived_at IS NULL
`

type GetGroupByIDRow struct {
	ID                   uuid.UUID
	Name                 string
	Description          pgtype.Text
	InviteCode           pgtype.Text
	InviteCodeExpiresAt  pgtype.Timestamptz
	RequireAdminApproval bool
	CreatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
}

func (q *Queries) GetGroupByID(ctx context.Context, id uuid.UUID) (GetGroupByIDRow, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i GetGroupByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.InviteCodeExpiresAt,
		&i.RequireAdminApproval,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getGroupByInviteCode = `-- name: GetGroupByInviteCode :one
SELECT id, name, description, invite_code, invite_code_expires_at, require_admin_approval, created_by, created_at, updated_at, archived_at
FROM groups
WHERE invite_code = $1 AND archived_at IS NULL
`

type GetGroupByInviteCodeRow struct {
	ID                   uuid.UUID
	Name                 string
	Description          pgtype.Text
	InviteCode           pgtype.Text
	InviteCodeExpiresAt  pgtype.Timestamptz
	RequireAdminApproval bool
	CreatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
}

func (q *Queries) GetGroupByInviteCode(ctx context.Context, inviteCode pgtype.Text) (GetGroupByInviteCodeRow, error) {
	row := q.db.QueryRow(ctx, getGroupByInviteCode, inviteCode)
	var i GetGroupByInviteCodeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.InviteCodeExpiresAt,
		&i.RequireAdminApproval,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT group_id, user_id, role, status, joined_at
FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type GetGroupMemberParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

type GetGroupMemberRow struct {
	GroupID  uuid.UUID
	UserID   uuid.UUID
	Role     string
	Status   string
	JoinedAt pgtype.Timestamptz
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GetGroupMemberRow, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GetGroupMemberRow
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const getGroupPreviewByInviteCode = `-- name: GetGroupPreviewByInviteCode :one
SELECT 
    g.name AS group_name,
    g.description AS group_description,
    COUNT(gm.user_id)::BIGINT AS member_count,
    u.name AS creator_name
FROM groups g
LEFT JOIN group_members gm ON g.id = gm.group_id AND gm.status = 'ACTIVE'
LEFT JOIN users u ON g.created_by = u.id
WHERE g.invite_code = $1 AND g.archived_at IS NULL
GROUP BY g.id, g.name, g.description, u.name
`

type GetGroupPreviewByInviteCodeRow struct {
	GroupName        string
	GroupDescription pgtype.Text
	MemberCount      int64
	CreatorName      pgtype.Text
}

func (q *Queries) GetGroupPreviewByInviteCode(ctx context.Context, inviteCode pgtype.Text) (GetGroupPreviewByInviteCodeRow, error) {
	row := q.db.QueryRow(ctx, getGroupPreviewByInviteCode, inviteCode)
	var i GetGroupPreviewByInviteCodeRow
	err := row.Scan(
		&i.GroupName,
		&i.GroupDescription,
		&i.MemberCount,
		&i.CreatorName,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT gm.group_id, gm.user_id, gm.role, gm.status, gm.joined_at, u.name, u.email, u.phone
FROM group_members gm
JOIN users u ON gm.user_id = u.id
WHERE gm.group_id = $1 AND ($2::text = '' OR gm.status = $2::text)
`

type ListGroupMembersParams struct {
	GroupID uuid.UUID
	Column2 string
}

type ListGroupMembersRow struct {
	GroupID  uuid.UUID
	UserID   uuid.UUID
	Role     string
	Status   string
	JoinedAt pgtype.Timestamptz
	Name     string
	Email    pgtype.Text
	Phone    pgtype.Text
}

func (q *Queries) ListGroupMembers(ctx context.Context, arg ListGroupMembersParams) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, arg.GroupID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
			&i.Name,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT g.id, g.name, g.description, g.invite_code, g.invite_code_expires_at, g.require_admin_approval, g.created_by, g.created_at, g.updated_at, g.archived_at
FROM groups g
JOIN group_members gm ON g.id = gm.group_id
WHERE gm.user_id = $1 AND gm.status = 'ACTIVE' AND g.archived_at IS NULL
`

type ListUserGroupsRow struct {
	ID                   uuid.UUID
	Name                 string
	Description          pgtype.Text
	InviteCode           pgtype.Text
	InviteCodeExpiresAt  pgtype.Timestamptz
	RequireAdminApproval bool
	CreatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
}

func (q *Queries) ListUserGroups(ctx context.Context, userID uuid.UUID) ([]ListUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, listUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserGroupsRow
	for rows.Next() {
		var i ListUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.InviteCode,
			&i.InviteCodeExpiresAt,
			&i.RequireAdminApproval,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroupsWithMembers = `-- name: ListUserGroupsWithMembers :many
SELECT
    g.id, g.name, g.description, g.invite_code, g.invite_code_expires_at, g.require_admin_approval, g.created_by,
    g.created_at, g.updated_at, g.archived_at,
    COALESCE(
        json_agg(
            json_build_object(
                'groupId',  gm2.group_id,
                'userId',   gm2.user_id,
                'role',     gm2.role,
                'status',   gm2.status,
                'joinedAt', gm2.joined_at,
                'name',     u.name,
                'email',    u.email,
                'phone',    u.phone
            ) ORDER BY gm2.joined_at
        ) FILTER (WHERE gm2.user_id IS NOT NULL),
        '[]'
    )::jsonb AS members
FROM groups g
JOIN group_members gm ON gm.group_id = g.id AND gm.user_id = $1 AND gm.status = 'ACTIVE'
LEFT JOIN group_members gm2 ON gm2.group_id = g.id
LEFT JOIN users u ON u.id = gm2.user_id
WHERE g.archived_at IS NULL
GROUP BY g.id
ORDER BY g.created_at DESC
`

type ListUserGroupsWithMembersRow struct {
	ID                   uuid.UUID
	Name                 string
	Description          pgtype.Text
	InviteCode           pgtype.Text
	InviteCodeExpiresAt  pgtype.Timestamptz
	RequireAdminApproval bool
	CreatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
	Members              []byte
}

func (q *Queries) ListUserGroupsWithMembers(ctx context.Context, userID uuid.UUID) ([]ListUserGroupsWithMembersRow, error) {
	rows, err := q.db.Query(ctx, listUserGroupsWithMembers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserGroupsWithMembersRow
	for rows.Next() {
		var i ListUserGroupsWithMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.InviteCode,
			&i.InviteCodeExpiresAt,
			&i.RequireAdminApproval,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Members,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroupsWithMembersPaginated = `-- name: ListUserGroupsWithMembersPaginated :many
SELECT
    g.id, g.name, g.description, g.invite_code, g.invite_code_expires_at, g.require_admin_approval, g.created_by,
    g.created_at, g.updated_at, g.archived_at,
    COALESCE(
        json_agg(
            json_build_object(
                'groupId',  gm2.group_id,
                'userId',   gm2.user_id,
                'role',     gm2.role,
                'status',   gm2.status,
                'joinedAt', gm2.joined_at,
                'name',     u.name,
                'email',    u.email,
                'phone',    u.phone
            ) ORDER BY gm2.joined_at
        ) FILTER (WHERE gm2.user_id IS NOT NULL),
        '[]'
    )::jsonb AS members
FROM groups g
JOIN group_members gm ON gm.group_id = g.id AND gm.user_id = $1 AND gm.status = 'ACTIVE'
LEFT JOIN group_members gm2 ON gm2.group_id = g.id
LEFT JOIN users u ON u.id = gm2.user_id
WHERE g.archived_at IS NULL
  AND (
    $3::TIMESTAMP WITH TIME ZONE IS NULL
    OR g.created_at < $3::TIMESTAMP WITH TIME ZONE
    OR (g.created_at = $3::TIMESTAMP WITH TIME ZONE AND g.id < $4::UUID)
  )
GROUP BY g.id
ORDER BY g.created_at DESC, g.id DESC
LIMIT $2
`

type ListUserGroupsWithMembersPaginatedParams struct {
	UserID  uuid.UUID
	Limit   int32
	Column3 pgtype.Timestamptz
	Column4 uuid.UUID
}

type ListUserGroupsWithMembersPaginatedRow struct {
	ID                   uuid.UUID
	Name                 string
	Description          pgtype.Text
	InviteCode           pgtype.Text
	InviteCodeExpiresAt  pgtype.Timestamptz
	RequireAdminApproval bool
	CreatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
	Members              []byte
}

func (q *Queries) ListUserGroupsWithMembersPaginated(ctx context.Context, arg ListUserGroupsWithMembersPaginatedParams) ([]ListUserGroupsWithMembersPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listUserGroupsWithMembersPaginated,
		arg.UserID,
		arg.Limit,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserGroupsWithMembersPaginatedRow
	for rows.Next() {
		var i ListUserGroupsWithMembersPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.InviteCode,
			&i.InviteCodeExpiresAt,
			&i.RequireAdminApproval,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
			&i.Members,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const resetGroupInviteCode = `-- name: ResetGroupInviteCode :one
UPDATE groups
SET invite_code = $2, invite_code_expires_at = $3, updated_at = NOW()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, name, description, invite_code, invite_code_expires_at, require_admin_approval, created_by, created_at, updated_at, archived_at
`

type ResetGroupInviteCodeParams struct {
	ID                  uuid.UUID
	InviteCode          pgtype.Text
	InviteCodeExpiresAt pgtype.Timestamptz
}

type ResetGroupInviteCodeRow struct {
	ID                   uuid.UUID
	Name                 string
	Description          pgtype.Text
	InviteCode           pgtype.Text
	InviteCodeExpiresAt  pgtype.Timestamptz
	RequireAdminApproval bool
	CreatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
}

func (q *Queries) ResetGroupInviteCode(ctx context.Context, arg ResetGroupInviteCodeParams) (ResetGroupInviteCodeRow, error) {
	row := q.db.QueryRow(ctx, resetGroupInviteCode, arg.ID, arg.InviteCode, arg.InviteCodeExpiresAt)
	var i ResetGroupInviteCodeRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.InviteCodeExpiresAt,
		&i.RequireAdminApproval,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = $2, description = $3, require_admin_approval = $4, updated_at = NOW()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, name, description, invite_code, invite_code_expires_at, require_admin_approval, created_by, created_at, updated_at, archived_at
`

type UpdateGroupParams struct {
	ID                   uuid.UUID
	Name                 string
	Description          pgtype.Text
	RequireAdminApproval bool
}

type UpdateGroupRow struct {
	ID                   uuid.UUID
	Name                 string
	Description          pgtype.Text
	InviteCode           pgtype.Text
	InviteCodeExpiresAt  pgtype.Timestamptz
	RequireAdminApproval bool
	CreatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (UpdateGroupRow, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.RequireAdminApproval,
	)
	var i UpdateGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.InviteCodeExpiresAt,
		&i.RequireAdminApproval,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateGroupMemberRole = `-- name: UpdateGroupMemberRole :exec
UPDATE group_members
SET role = $3
WHERE group_id = $1 AND user_id = $2
`

type UpdateGroupMemberRoleParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
	Role    string
}

func (q *Queries) UpdateGroupMemberRole(ctx context.Context, arg UpdateGroupMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateGroupMemberRole, arg.GroupID, arg.UserID, arg.Role)
	return err
}

const updateMemberStatus = `-- name: UpdateMemberStatus :exec
UPDATE group_members
SET status = $3
WHERE group_id = $1 AND user_id = $2
`

type UpdateMemberStatusParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
	Status  string
}

func (q *Queries) UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) error {
	_, err := q.db.Exec(ctx, updateMemberStatus, arg.GroupID, arg.UserID, arg.Status)
	return err
}
