// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: group.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id, role, joined_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (group_id, user_id) DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
	Role    string
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.Role)
	return err
}

const archiveGroup = `-- name: ArchiveGroup :exec
UPDATE groups
SET archived_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ArchiveGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, archiveGroup, id)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name, description, invite_code, created_by, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
RETURNING id, name, description, invite_code, created_by, created_at, updated_at, archived_at
`

type CreateGroupParams struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
	InviteCode  pgtype.Text
	CreatedBy   pgtype.UUID
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.InviteCode,
		arg.CreatedBy,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, description, invite_code, created_by, created_at, updated_at, archived_at
FROM groups
WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getGroupByInviteCode = `-- name: GetGroupByInviteCode :one
SELECT id, name, description, invite_code, created_by, created_at, updated_at, archived_at
FROM groups
WHERE invite_code = $1 AND archived_at IS NULL
`

func (q *Queries) GetGroupByInviteCode(ctx context.Context, inviteCode pgtype.Text) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByInviteCode, inviteCode)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT group_id, user_id, role, joined_at
FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type GetGroupMemberParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT gm.group_id, gm.user_id, gm.role, gm.joined_at, u.name, u.email, u.phone
FROM group_members gm
JOIN users u ON gm.user_id = u.id
WHERE gm.group_id = $1
`

type ListGroupMembersRow struct {
	GroupID  uuid.UUID
	UserID   uuid.UUID
	Role     string
	JoinedAt pgtype.Timestamptz
	Name     string
	Email    pgtype.Text
	Phone    pgtype.Text
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Name,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT g.id, g.name, g.description, g.invite_code, g.created_by, g.created_at, g.updated_at, g.archived_at
FROM groups g
JOIN group_members gm ON g.id = gm.group_id
WHERE gm.user_id = $1 AND g.archived_at IS NULL
`

func (q *Queries) ListUserGroups(ctx context.Context, userID uuid.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.InviteCode,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name = $2, description = $3, updated_at = NOW()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, name, description, invite_code, created_by, created_at, updated_at, archived_at
`

type UpdateGroupParams struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup, arg.ID, arg.Name, arg.Description)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.InviteCode,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateGroupMemberRole = `-- name: UpdateGroupMemberRole :exec
UPDATE group_members
SET role = $3
WHERE group_id = $1 AND user_id = $2
`

type UpdateGroupMemberRoleParams struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
	Role    string
}

func (q *Queries) UpdateGroupMemberRole(ctx context.Context, arg UpdateGroupMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateGroupMemberRole, arg.GroupID, arg.UserID, arg.Role)
	return err
}
