// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (key, user_id, request_path, request_method, request_hash, response_code, response_headers, response_body, locked_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
ON CONFLICT (user_id, key) DO NOTHING
RETURNING id, key, user_id, request_path, request_method, request_hash, response_code, response_headers, response_body, created_at, locked_at
`

type CreateIdempotencyKeyParams struct {
	Key             string
	UserID          uuid.UUID
	RequestPath     string
	RequestMethod   string
	RequestHash     string
	ResponseCode    pgtype.Int4
	ResponseHeaders []byte
	ResponseBody    []byte
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.Key,
		arg.UserID,
		arg.RequestPath,
		arg.RequestMethod,
		arg.RequestHash,
		arg.ResponseCode,
		arg.ResponseHeaders,
		arg.ResponseBody,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.RequestPath,
		&i.RequestMethod,
		&i.RequestHash,
		&i.ResponseCode,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.LockedAt,
	)
	return i, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :exec
DELETE FROM idempotency_keys
WHERE created_at < $1
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys, createdAt)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, key, user_id, request_path, request_method, request_hash, response_code, response_headers, response_body, created_at, locked_at
FROM idempotency_keys
WHERE user_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	UserID uuid.UUID
	Key    string
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.UserID, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.RequestPath,
		&i.RequestMethod,
		&i.RequestHash,
		&i.ResponseCode,
		&i.ResponseHeaders,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.LockedAt,
	)
	return i, err
}

const updateIdempotencyKeyResponse = `-- name: UpdateIdempotencyKeyResponse :exec
UPDATE idempotency_keys
SET response_code = $3, response_headers = $4, response_body = $5
WHERE user_id = $1 AND key = $2
`

type UpdateIdempotencyKeyResponseParams struct {
	UserID          uuid.UUID
	Key             string
	ResponseCode    pgtype.Int4
	ResponseHeaders []byte
	ResponseBody    []byte
}

func (q *Queries) UpdateIdempotencyKeyResponse(ctx context.Context, arg UpdateIdempotencyKeyResponseParams) error {
	_, err := q.db.Exec(ctx, updateIdempotencyKeyResponse,
		arg.UserID,
		arg.Key,
		arg.ResponseCode,
		arg.ResponseHeaders,
		arg.ResponseBody,
	)
	return err
}
