// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID          uuid.UUID
	ActorID     pgtype.UUID
	ActionType  string
	EntityType  string
	EntityID    pgtype.UUID
	GroupID     pgtype.UUID
	Payload     []byte
	CreatedAt   pgtype.Timestamptz
	Description string
	Metadata    []byte
}

type ActivityVisibility struct {
	ActivityID uuid.UUID
	UserID     uuid.UUID
}

type AppVersion struct {
	ID                  int32
	MinSupportedVersion string
	LatestVersion       string
	ForceUpdate         bool
	IosUpdateUrl        string
	AndroidUpdateUrl    string
	UpdateMessage       string
}

type ConfigVersion struct {
	ID          int32
	VersionHash string
	UpdatedAt   pgtype.Timestamptz
}

type Currency struct {
	Code          string
	Symbol        string
	Name          string
	DecimalPlaces int32
	IsDefault     bool
	IsActive      bool
}

type EntityTombstone struct {
	ID          uuid.UUID
	EntityType  string
	EntityID    uuid.UUID
	UserID      uuid.UUID
	SyncVersion int64
	DeletedAt   pgtype.Timestamptz
}

type Expense struct {
	ID          uuid.UUID
	Description string
	Amount      pgtype.Numeric
	Currency    string
	Category    string
	GroupID     pgtype.UUID
	PaidBy      uuid.UUID
	CreatedBy   uuid.UUID
	IsPayment   bool
	SpentAt     pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	SyncVersion int64
}

type ExpenseCategory struct {
	ID           string
	Name         string
	IconUrl      string
	DisplayOrder int32
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

type ExpenseSplit struct {
	ExpenseID  uuid.UUID
	UserID     uuid.UUID
	Amount     pgtype.Numeric
	SplitType  string
	SplitValue pgtype.Numeric
}

type FeatureFlag struct {
	Key         string
	IsEnabled   bool
	Description pgtype.Text
}

type Friendship struct {
	UserID       uuid.UUID
	FriendID     uuid.UUID
	Status       string
	ActionUserID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	SyncVersion  int64
}

type Group struct {
	ID                   uuid.UUID
	Name                 string
	Description          pgtype.Text
	InviteCode           pgtype.Text
	InviteCodeExpiresAt  pgtype.Timestamptz
	RequireAdminApproval bool
	CreatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
	SyncVersion          int64
	IconUrl              pgtype.Text
}

type GroupMember struct {
	GroupID  uuid.UUID
	UserID   uuid.UUID
	Role     string
	Status   string
	JoinedAt pgtype.Timestamptz
}

type LegalConfig struct {
	ID                int32
	TermsOfServiceUrl string
	PrivacyPolicyUrl  string
	FaqUrl            string
	SupportEmail      string
}

type MaintenanceStatus struct {
	ID               int32
	InMaintenance    bool
	ReadOnlyMode     bool
	Message          string
	EstimatedEndTime pgtype.Timestamptz
}

type Notification struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ActorID    pgtype.UUID
	AlertType  string
	EntityType string
	EntityID   uuid.UUID
	GroupID    pgtype.UUID
	Payload    []byte
	IsRead     bool
	CreatedAt  pgtype.Timestamptz
	ActivityID pgtype.UUID
	Title      string
	Content    string
	Type       string
}

type SystemLimit struct {
	ID                      int32
	MaxExpenseAmount        pgtype.Numeric
	MaxGroupMembers         int32
	MaxSplitParticipants    int32
	MaxReceiptSizeMb        int32
	AllowedReceiptMimeTypes []string
}

type User struct {
	ID              uuid.UUID
	FirebaseUid     string
	Email           pgtype.Text
	Phone           pgtype.Text
	Name            string
	DefaultCurrency string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	AvatarUrl       pgtype.Text
}

type UserSetting struct {
	UserID                   uuid.UUID
	AutoAcceptFriendRequests bool
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}
