// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MemberRole string

const (
	MemberRoleADMIN  MemberRole = "ADMIN"
	MemberRoleMEMBER MemberRole = "MEMBER"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole
	Valid      bool // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type MemberStatus string

const (
	MemberStatusACTIVE   MemberStatus = "ACTIVE"
	MemberStatusPENDING  MemberStatus = "PENDING"
	MemberStatusREJECTED MemberStatus = "REJECTED"
)

func (e *MemberStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberStatus(s)
	case string:
		*e = MemberStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberStatus: %T", src)
	}
	return nil
}

type NullMemberStatus struct {
	MemberStatus MemberStatus
	Valid        bool // Valid is true if MemberStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MemberStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberStatus), nil
}

type Activity struct {
	ID          uuid.UUID
	GroupID     pgtype.UUID
	ActorID     pgtype.UUID
	ActionType  string
	Description string
	CreatedAt   pgtype.Timestamptz
	EntityType  string
	EntityID    pgtype.UUID
	Metadata    []byte
}

type ActivityVisibility struct {
	ActivityID uuid.UUID
	UserID     uuid.UUID
}

type AppVersion struct {
	ID                  int32
	MinSupportedVersion string
	LatestVersion       string
	ForceUpdate         bool
	IosUpdateUrl        string
	AndroidUpdateUrl    string
	UpdateMessage       string
}

type ConfigVersion struct {
	ID          int32
	VersionHash string
	UpdatedAt   pgtype.Timestamptz
}

type Currency struct {
	Code          string
	Symbol        string
	Name          string
	DecimalPlaces int32
	IsDefault     bool
	IsActive      bool
}

type Expense struct {
	ID          uuid.UUID
	Description string
	Amount      pgtype.Numeric
	Currency    string
	Category    string
	GroupID     pgtype.UUID
	PaidBy      uuid.UUID
	CreatedBy   uuid.UUID
	IsPayment   bool
	SpentAt     pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type ExpenseCategory struct {
	ID           string
	Name         string
	IconUrl      string
	DisplayOrder int32
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

type ExpenseSplit struct {
	ExpenseID  uuid.UUID
	UserID     uuid.UUID
	Amount     pgtype.Numeric
	SplitType  string
	SplitValue pgtype.Numeric
}

type FeatureFlag struct {
	Key         string
	IsEnabled   bool
	Description pgtype.Text
}

type Friendship struct {
	UserID    uuid.UUID
	FriendID  uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type Group struct {
	ID                   uuid.UUID
	Name                 string
	Description          pgtype.Text
	InviteCode           pgtype.Text
	CreatedBy            pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	ArchivedAt           pgtype.Timestamptz
	InviteCodeExpiresAt  pgtype.Timestamptz
	RequireAdminApproval bool
}

type GroupMember struct {
	GroupID  uuid.UUID
	UserID   uuid.UUID
	JoinedAt pgtype.Timestamptz
	Role     MemberRole
	Status   MemberStatus
}

type LegalConfig struct {
	ID                int32
	TermsOfServiceUrl string
	PrivacyPolicyUrl  string
	FaqUrl            string
	SupportEmail      string
}

type MaintenanceStatus struct {
	ID               int32
	InMaintenance    bool
	ReadOnlyMode     bool
	Message          string
	EstimatedEndTime pgtype.Timestamptz
}

type Notification struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ActorID    pgtype.UUID
	ActivityID pgtype.UUID
	Title      string
	Content    string
	IsRead     bool
	CreatedAt  pgtype.Timestamptz
}

type SystemLimit struct {
	ID                      int32
	MaxExpenseAmount        pgtype.Numeric
	MaxGroupMembers         int32
	MaxSplitParticipants    int32
	MaxReceiptSizeMb        int32
	AllowedReceiptMimeTypes []string
}

type User struct {
	ID              uuid.UUID
	FirebaseUid     string
	Email           pgtype.Text
	Phone           pgtype.Text
	Name            string
	DefaultCurrency string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
