// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (id, user_id, actor_id, activity_id, title, content, is_read, created_at)
VALUES ($1, $2, $3, $4, $5, $6, FALSE, NOW())
RETURNING id, user_id, actor_id, activity_id, title, content, is_read, created_at
`

type CreateNotificationParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ActorID    pgtype.UUID
	ActivityID pgtype.UUID
	Title      string
	Content    string
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.UserID,
		arg.ActorID,
		arg.ActivityID,
		arg.Title,
		arg.Content,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActorID,
		&i.ActivityID,
		&i.Title,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const listUserNotifications = `-- name: ListUserNotifications :many
SELECT n.id, n.user_id, n.actor_id, n.activity_id, n.title, n.content, n.is_read, n.created_at, u.name as actor_name
FROM notifications n
LEFT JOIN users u ON n.actor_id = u.id
WHERE n.user_id = $1
ORDER BY n.created_at DESC
`

type ListUserNotificationsRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ActorID    pgtype.UUID
	ActivityID pgtype.UUID
	Title      string
	Content    string
	IsRead     bool
	CreatedAt  pgtype.Timestamptz
	ActorName  pgtype.Text
}

func (q *Queries) ListUserNotifications(ctx context.Context, userID uuid.UUID) ([]ListUserNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listUserNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserNotificationsRow
	for rows.Next() {
		var i ListUserNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActorID,
			&i.ActivityID,
			&i.Title,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE user_id = $1
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE id = $1 AND user_id = $2
`

type MarkNotificationAsReadParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	return err
}
