// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_settings.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createDefaultUserSettings = `-- name: CreateDefaultUserSettings :exec
INSERT INTO user_settings (user_id, auto_accept_friend_requests, created_at, updated_at)
VALUES ($1, FALSE, NOW(), NOW())
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) CreateDefaultUserSettings(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createDefaultUserSettings, userID)
	return err
}

const getUserSettings = `-- name: GetUserSettings :one
SELECT user_id, auto_accept_friend_requests, created_at, updated_at
FROM user_settings
WHERE user_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.AutoAcceptFriendRequests,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserSettings = `-- name: UpsertUserSettings :one
INSERT INTO user_settings (user_id, auto_accept_friend_requests, created_at, updated_at)
VALUES ($1, $2, NOW(), NOW())
ON CONFLICT (user_id) DO UPDATE
SET auto_accept_friend_requests = EXCLUDED.auto_accept_friend_requests,
    updated_at = NOW()
RETURNING user_id, auto_accept_friend_requests, created_at, updated_at
`

type UpsertUserSettingsParams struct {
	UserID                   uuid.UUID
	AutoAcceptFriendRequests bool
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, upsertUserSettings, arg.UserID, arg.AutoAcceptFriendRequests)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.AutoAcceptFriendRequests,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
