// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFriendship = `-- name: CreateFriendship :exec
INSERT INTO friendships (user_id, friend_id, status, action_user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
ON CONFLICT (user_id, friend_id) DO UPDATE
SET status = EXCLUDED.status,
    action_user_id = EXCLUDED.action_user_id,
    updated_at = NOW()
`

type CreateFriendshipParams struct {
	UserID       uuid.UUID
	FriendID     uuid.UUID
	Status       string
	ActionUserID pgtype.UUID
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) error {
	_, err := q.db.Exec(ctx, createFriendship,
		arg.UserID,
		arg.FriendID,
		arg.Status,
		arg.ActionUserID,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, firebase_uid, email, phone, name, default_currency, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
RETURNING id, firebase_uid, email, phone, name, default_currency, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	ID              uuid.UUID
	FirebaseUid     string
	Email           pgtype.Text
	Phone           pgtype.Text
	Name            string
	DefaultCurrency string
}

type CreateUserRow struct {
	ID              uuid.UUID
	FirebaseUid     string
	Email           pgtype.Text
	Phone           pgtype.Text
	Name            string
	DefaultCurrency string
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FirebaseUid,
		arg.Email,
		arg.Phone,
		arg.Name,
		arg.DefaultCurrency,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.DefaultCurrency,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships
WHERE (user_id = $1 AND friend_id = $2) OR (user_id = $2 AND friend_id = $1)
`

type DeleteFriendshipParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.Exec(ctx, deleteFriendship, arg.UserID, arg.FriendID)
	return err
}

const getFriendTombstonesBySequence = `-- name: GetFriendTombstonesBySequence :many
SELECT entity_id, sync_version
FROM entity_tombstones
WHERE entity_type = 'FRIENDSHIP'
  AND user_id = $1
  AND sync_version > $2
ORDER BY sync_version ASC
LIMIT $3
`

type GetFriendTombstonesBySequenceParams struct {
	UserID      uuid.UUID
	SyncVersion int64
	Limit       int32
}

type GetFriendTombstonesBySequenceRow struct {
	EntityID    uuid.UUID
	SyncVersion int64
}

func (q *Queries) GetFriendTombstonesBySequence(ctx context.Context, arg GetFriendTombstonesBySequenceParams) ([]GetFriendTombstonesBySequenceRow, error) {
	rows, err := q.db.Query(ctx, getFriendTombstonesBySequence, arg.UserID, arg.SyncVersion, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFriendTombstonesBySequenceRow
	for rows.Next() {
		var i GetFriendTombstonesBySequenceRow
		if err := rows.Scan(&i.EntityID, &i.SyncVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFriendship = `-- name: GetFriendship :one
SELECT user_id, friend_id, status, action_user_id, created_at, updated_at
FROM friendships
WHERE (user_id = $1 AND friend_id = $2) OR (user_id = $2 AND friend_id = $1)
`

type GetFriendshipParams struct {
	UserID   uuid.UUID
	FriendID uuid.UUID
}

type GetFriendshipRow struct {
	UserID       uuid.UUID
	FriendID     uuid.UUID
	Status       string
	ActionUserID pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) GetFriendship(ctx context.Context, arg GetFriendshipParams) (GetFriendshipRow, error) {
	row := q.db.QueryRow(ctx, getFriendship, arg.UserID, arg.FriendID)
	var i GetFriendshipRow
	err := row.Scan(
		&i.UserID,
		&i.FriendID,
		&i.Status,
		&i.ActionUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailOrPhone = `-- name: GetUserByEmailOrPhone :one
SELECT id, firebase_uid, email, phone, name, default_currency, avatar_url, created_at, updated_at
FROM users
WHERE email = $1 OR phone = $2
`

type GetUserByEmailOrPhoneParams struct {
	Email pgtype.Text
	Phone pgtype.Text
}

type GetUserByEmailOrPhoneRow struct {
	ID              uuid.UUID
	FirebaseUid     string
	Email           pgtype.Text
	Phone           pgtype.Text
	Name            string
	DefaultCurrency string
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetUserByEmailOrPhone(ctx context.Context, arg GetUserByEmailOrPhoneParams) (GetUserByEmailOrPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailOrPhone, arg.Email, arg.Phone)
	var i GetUserByEmailOrPhoneRow
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.DefaultCurrency,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, firebase_uid, email, phone, name, default_currency, avatar_url, created_at, updated_at
FROM users
WHERE firebase_uid = $1
`

type GetUserByFirebaseUIDRow struct {
	ID              uuid.UUID
	FirebaseUid     string
	Email           pgtype.Text
	Phone           pgtype.Text
	Name            string
	DefaultCurrency string
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (GetUserByFirebaseUIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i GetUserByFirebaseUIDRow
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.DefaultCurrency,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, firebase_uid, email, phone, name, default_currency, avatar_url, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID              uuid.UUID
	FirebaseUid     string
	Email           pgtype.Text
	Phone           pgtype.Text
	Name            string
	DefaultCurrency string
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.DefaultCurrency,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWithSettingsByEmailOrPhone = `-- name: GetUserWithSettingsByEmailOrPhone :one
SELECT u.id, u.firebase_uid, u.email, u.phone, u.name, u.default_currency, u.created_at, u.updated_at,
       COALESCE(s.auto_accept_friend_requests, FALSE)::BOOLEAN AS auto_accept_friend_requests
FROM users u
LEFT JOIN user_settings s ON u.id = s.user_id
WHERE u.email = $1 OR u.phone = $2
`

type GetUserWithSettingsByEmailOrPhoneParams struct {
	Email pgtype.Text
	Phone pgtype.Text
}

type GetUserWithSettingsByEmailOrPhoneRow struct {
	ID                       uuid.UUID
	FirebaseUid              string
	Email                    pgtype.Text
	Phone                    pgtype.Text
	Name                     string
	DefaultCurrency          string
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	AutoAcceptFriendRequests bool
}

func (q *Queries) GetUserWithSettingsByEmailOrPhone(ctx context.Context, arg GetUserWithSettingsByEmailOrPhoneParams) (GetUserWithSettingsByEmailOrPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserWithSettingsByEmailOrPhone, arg.Email, arg.Phone)
	var i GetUserWithSettingsByEmailOrPhoneRow
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.DefaultCurrency,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoAcceptFriendRequests,
	)
	return i, err
}

const listFriends = `-- name: ListFriends :many
SELECT u.id, u.firebase_uid, u.email, u.phone, u.name, u.default_currency, u.created_at, u.updated_at
FROM users u
WHERE u.id IN (
    SELECT f.friend_id FROM friendships f WHERE f.user_id = $1 AND f.status = 'ACCEPTED'
    UNION
    SELECT f.user_id FROM friendships f WHERE f.friend_id = $1 AND f.status = 'ACCEPTED'
)
`

type ListFriendsRow struct {
	ID              uuid.UUID
	FirebaseUid     string
	Email           pgtype.Text
	Phone           pgtype.Text
	Name            string
	DefaultCurrency string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListFriends(ctx context.Context, userID uuid.UUID) ([]ListFriendsRow, error) {
	rows, err := q.db.Query(ctx, listFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsRow
	for rows.Next() {
		var i ListFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirebaseUid,
			&i.Email,
			&i.Phone,
			&i.Name,
			&i.DefaultCurrency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriendsByStatus = `-- name: ListFriendsByStatus :many
SELECT u.id, u.firebase_uid, u.email, u.phone, u.name, u.default_currency, u.created_at, u.updated_at, f.status, f.action_user_id
FROM users u
JOIN friendships f ON (
    (f.user_id = $1 AND f.friend_id = u.id) OR
    (f.friend_id = $1 AND f.user_id = u.id)
)
WHERE f.status = $2
`

type ListFriendsByStatusParams struct {
	UserID uuid.UUID
	Status string
}

type ListFriendsByStatusRow struct {
	ID              uuid.UUID
	FirebaseUid     string
	Email           pgtype.Text
	Phone           pgtype.Text
	Name            string
	DefaultCurrency string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Status          string
	ActionUserID    pgtype.UUID
}

func (q *Queries) ListFriendsByStatus(ctx context.Context, arg ListFriendsByStatusParams) ([]ListFriendsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listFriendsByStatus, arg.UserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsByStatusRow
	for rows.Next() {
		var i ListFriendsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.FirebaseUid,
			&i.Email,
			&i.Phone,
			&i.Name,
			&i.DefaultCurrency,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.ActionUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriendsPaginated = `-- name: ListFriendsPaginated :many
SELECT u.id, u.firebase_uid, u.email, u.phone, u.name, u.default_currency, u.created_at, u.updated_at
FROM users u
WHERE u.id IN (
    SELECT f.friend_id FROM friendships f WHERE f.user_id = $1 AND f.status = 'ACCEPTED'
    UNION
    SELECT f.user_id FROM friendships f WHERE f.friend_id = $1 AND f.status = 'ACCEPTED'
)
AND (
  $3::TIMESTAMP WITH TIME ZONE IS NULL
  OR u.created_at < $3::TIMESTAMP WITH TIME ZONE
  OR (u.created_at = $3::TIMESTAMP WITH TIME ZONE AND u.id < $4::UUID)
)
ORDER BY u.created_at DESC, u.id DESC
LIMIT $2
`

type ListFriendsPaginatedParams struct {
	UserID  uuid.UUID
	Limit   int32
	Column3 pgtype.Timestamptz
	Column4 uuid.UUID
}

type ListFriendsPaginatedRow struct {
	ID              uuid.UUID
	FirebaseUid     string
	Email           pgtype.Text
	Phone           pgtype.Text
	Name            string
	DefaultCurrency string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListFriendsPaginated(ctx context.Context, arg ListFriendsPaginatedParams) ([]ListFriendsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listFriendsPaginated,
		arg.UserID,
		arg.Limit,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFriendsPaginatedRow
	for rows.Next() {
		var i ListFriendsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.FirebaseUid,
			&i.Email,
			&i.Phone,
			&i.Name,
			&i.DefaultCurrency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncFriendsBySequence = `-- name: SyncFriendsBySequence :many
SELECT f.user_id, f.friend_id, f.status, f.action_user_id, f.created_at, f.updated_at, f.sync_version
FROM friendships f
WHERE f.sync_version > $1
  AND (f.user_id = $2 OR f.friend_id = $2)
ORDER BY f.sync_version ASC
LIMIT $3
`

type SyncFriendsBySequenceParams struct {
	SyncVersion int64
	UserID      uuid.UUID
	Limit       int32
}

func (q *Queries) SyncFriendsBySequence(ctx context.Context, arg SyncFriendsBySequenceParams) ([]Friendship, error) {
	rows, err := q.db.Query(ctx, syncFriendsBySequence, arg.SyncVersion, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Friendship
	for rows.Next() {
		var i Friendship
		if err := rows.Scan(
			&i.UserID,
			&i.FriendID,
			&i.Status,
			&i.ActionUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SyncVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFriendshipStatus = `-- name: UpdateFriendshipStatus :exec
UPDATE friendships
SET status = $3,
    action_user_id = $4,
    updated_at = NOW()
WHERE (user_id = $1 AND friend_id = $2) OR (user_id = $2 AND friend_id = $1)
`

type UpdateFriendshipStatusParams struct {
	UserID       uuid.UUID
	FriendID     uuid.UUID
	Status       string
	ActionUserID pgtype.UUID
}

func (q *Queries) UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) error {
	_, err := q.db.Exec(ctx, updateFriendshipStatus,
		arg.UserID,
		arg.FriendID,
		arg.Status,
		arg.ActionUserID,
	)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $2, default_currency = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, firebase_uid, email, phone, name, default_currency, avatar_url, created_at, updated_at
`

type UpdateUserParams struct {
	ID              uuid.UUID
	Name            string
	DefaultCurrency string
}

type UpdateUserRow struct {
	ID              uuid.UUID
	FirebaseUid     string
	Email           pgtype.Text
	Phone           pgtype.Text
	Name            string
	DefaultCurrency string
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.Name, arg.DefaultCurrency)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.DefaultCurrency,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :one
UPDATE users
SET avatar_url = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, firebase_uid, email, phone, name, default_currency, avatar_url, created_at, updated_at
`

type UpdateUserAvatarParams struct {
	ID        uuid.UUID
	AvatarUrl pgtype.Text
}

type UpdateUserAvatarRow struct {
	ID              uuid.UUID
	FirebaseUid     string
	Email           pgtype.Text
	Phone           pgtype.Text
	Name            string
	DefaultCurrency string
	AvatarUrl       pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) (UpdateUserAvatarRow, error) {
	row := q.db.QueryRow(ctx, updateUserAvatar, arg.ID, arg.AvatarUrl)
	var i UpdateUserAvatarRow
	err := row.Scan(
		&i.ID,
		&i.FirebaseUid,
		&i.Email,
		&i.Phone,
		&i.Name,
		&i.DefaultCurrency,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
